name: Publish packages from tags

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      allowNoTags:
        description: 'Allow running without tags'
        required: false
        default: 'false'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Detect pushed tags
        run: |
          git fetch --tags

          TAGS=$(git tag --points-at HEAD)

          if [ -z "$TAGS" ]; then
            if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
              echo "Manual run — continuing without tags"
            else
              echo "No tags on this commit — skipping"
              exit 0
            fi
          fi

          echo "Tags:"
          echo "$TAGS"

      - uses: actions/setup-node@v6
        with:
          node-version: 22.17.1
          cache: 'yarn'

      - name: Installere dependencies
        run: yarn install --immutable
        env:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build packages
        run: yarn build

      - name: Publish packages from existing tags
        run: lerna publish from-git --yes
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
